bcarmard_apivdm_home:
    pattern: /apivdm
    defaults: { _controller: BcarmardTestIAdvizeBundle:ApiVdm:index }
    
    
bcarmard_apivdm_load:
    pattern: /apivdm/load
    defaults: { _controller: BcarmardTestIAdvizeBundle:ApiVdm:load }
    