<?php

namespace Bcarmard\TestIAdvizeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApiVdmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiVdmRepository extends EntityRepository
{
}
